// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWKBj4QeO5OLffC6JE3xImtuXz0745ooY',
    appId: '1:523791945031:web:273467b8701e17adc05062',
    messagingSenderId: '523791945031',
    projectId: 'store-76ad6',
    authDomain: 'store-76ad6.firebaseapp.com',
    storageBucket: 'store-76ad6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuPYP0ZQd3Q5GRaqUawKJcf4_uau2YJ6E',
    appId: '1:523791945031:android:7eff963c4a07a4aac05062',
    messagingSenderId: '523791945031',
    projectId: 'store-76ad6',
    storageBucket: 'store-76ad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAW9PRm8FvkNLe3U29ces8hxGS5jmUki8',
    appId: '1:523791945031:ios:e386a03ce3e57c9bc05062',
    messagingSenderId: '523791945031',
    projectId: 'store-76ad6',
    storageBucket: 'store-76ad6.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAW9PRm8FvkNLe3U29ces8hxGS5jmUki8',
    appId: '1:523791945031:ios:e386a03ce3e57c9bc05062',
    messagingSenderId: '523791945031',
    projectId: 'store-76ad6',
    storageBucket: 'store-76ad6.appspot.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWKBj4QeO5OLffC6JE3xImtuXz0745ooY',
    appId: '1:523791945031:web:59919b72ede252dbc05062',
    messagingSenderId: '523791945031',
    projectId: 'store-76ad6',
    authDomain: 'store-76ad6.firebaseapp.com',
    storageBucket: 'store-76ad6.appspot.com',
  );
}
